### ISSUE TITLE
login is not firing up

### ISSUE THREAD

**Issue by sudhanshu-pantelwar** [zyra/cordova-plugin-linkedin#10]
I am using this plugin in ionic 2.
this is what I did:
1. created a new app on linkedin.
2. Under the mobile section, pasted package name from config.xml file and then generated hash using the following command:
keytool -exportcert -alias ALIAS_HERE -keystore path/to/mykey.keystore | openssl sha1 -binary | openssl base64
and pasted the hash in the package hash.
3. now when I am trying to login, it's not firing up at all.
getActiveSession is working but not the login.

**Comment by ihadeed** [comment]
Hey there,

- do you have the LinkedIn app installed on the device you're testing on?
- do you see any errors in the console?
- do any of the callbacks get invoked?
