### ISSUE TITLE
getActiveSession should also return userid

### ISSUE THREAD

**Issue by naveedahmed1** [zyra/cordova-plugin-linkedin#12]
GooglePlus and Facebook cordova plugins both returns userid or unique identifier of the user along with access token.

It would be great if getActiveSession method could also return the userid.

**Comment by ihadeed** [comment]
IIRC the SDK only has the access token stored in memory. I will check again to see if the user ID is there. The functionality that `getActiveSession` does is not even officially supported by the SDK.

**Comment by ihadeed** [comment]
I just double checked... It's not possible to retrieve the user's ID through the session manager. I suggest you make a get request to `people/~` to get the user's profile which contains their ID.
