### ISSUE TITLE
Access Token validation error

### ISSUE THREAD

**Issue by naveedahmed1** [zyra/cordova-plugin-linkedin#13]
Hi,

I am unable to validate the generated Access Token in my web app:

Usually the below request should be successful for valid access tokens:

`https://api.linkedin.com/v1/people/~?oauth2_access_token=YOUR-ACCESS-TOKEN`

But when I try it with the token generated through this plugin, it always return below error:

```
<error>
<status>401</status>
<timestamp>1494961358990</timestamp>
<request-id>Z0HHYBHVDS</request-id>
<error-code>0</error-code>
<message>Unable to verify access token</message>
</error>
```

**Comment by ihadeed** [comment]
See the link in this comment https://github.com/zyra/cordova-plugin-linkedin/issues/1#issuecomment-291118566
