### ISSUE TITLE
Login success callback not firing

### ISSUE THREAD

**Issue by popovicidinu** [zyra/cordova-plugin-linkedin#14]
Hi. 

I have an issue with this plugin on a project I'm working. No matter what call I make via the plugin, the promise always looks like this: {"__zone_symbol__state":null,"__zone_symbol__value":[]}

global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:
    Node       : v6.10.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

**Comment by ihadeed** [comment]
Are you calling `.then()` on the promise?

**Comment by popovicidinu** [comment]
I'm doing something like this:

`this.linkedIn.login(['r_basicprofile', 'r_emailaddress'], false)
      .then( (success) => {
         // trying to console log here
      })
      .catch( (error) => {
    
        console.log(error);
    });`

The problem is that nothing is outputting, no errors, nothing. When my function is being called, I do see the LinkedIn loading splashscreen for a bit, but after that it disappears.

**Comment by ihadeed** [comment]
This issue was moved to driftyco/ionic-native#1587

**Comment by ihadeed** [comment]
Well this is strange. When I build the project using the Ionic/Cordova CLI, I am able to reproduce the issue you mentioned. But when I build the project using Android Studio it works fine.

**Comment by popovicidinu** [comment]
@ihadeed I tested all day long trying to get this working and from all my tests only once I saw the splash screen asking to approve that I allow the app to use my LinkedIn data.  I can't​ recall if it was via the android simulator or Cordova CLI. 

I kept thinking my build is wrong or I'm doing something wrong hence it worked once, but not after that.

**Comment by ihadeed** [comment]
I'll look into it when I get a chance.

**Comment by ihadeed** [comment]
Quick update...

I'm 99% sure the problem has nothing to do with this repo. Something must have changed with Cordova Android (most likely the issue) or the LinkedIn app (could be the issue, but not likely). 

I just did more debugging and I'm finding out that when the LinkedIn SDK is calling `startActivityForResult`, it's not hearing back from the LinkedIn app at all. It works the first time only but after that the app stops listening for any activity results.

**Comment by popovicidinu** [comment]
@ihadeed 

I'd like to debug the plugin myself to see what is happening and maybe I can figure out a solution for this, but I'm rather new to all of this. If you could point me in the right direction (what tools to install, how to run & test, etc) I'd much appreciate it. I really want to get this working as it seems it's the only plugin that can do what I need. 

Thanks.

**Comment by ihadeed** [comment]
1. Create a blank Cordova/Ionic App
2. Add minimal code to make your development easier
    - buttons to do an action (i.e. a button that calls `cordova.plugins.LinkedIn.login(....)`)
3. Install this plugin
4. Build the app (if using Ionic) to have the www directory ready
5. Add Android platform and run `cordova build android`
6. Open `/platforms/android/` with Android Studio
7. Run/Debug the app from Android Studio
8. Edit `/src/com/zyramedia/cordova/linkedin/LinkedIn.java` to:
    - add debug/break points
    - edit code to experiment with different things
    - click the debug button again to reload the app on device/emulator

**Comment by popovicidinu** [comment]
@ihadeed 

I managed to get it working for the first time, but after that I get back something like this:

```
05-25 09:48:00.013  4910  4910 D CordovaActivity: Incoming Result. Request code = 3672
05-25 09:48:00.013  4910  4910 W CordovaInterfaceImpl: Got an activity result, but no plugin was registered to receive it.
```

**Comment by ihadeed** [comment]
thanks @imcu 

Just published a new version with this fix `cordova-plugin-linkedin@1.2.1`

**Comment by TitikshaDaga** [comment]
Hi. I am facing a similar issue. The linkedin app opens up and the result of linkedin.login is ok but it doesn't get into the then function. It was working a month ago but now it isn't.

` this.linkedin.login(["r_basicprofile", "r_emailaddress"], true).then(results => {
      console.log('linkedin signup::results ', results)
      this.linkedin.getRequest('people/~:(id,email-address,first-name,last-name,formatted-name,picture-url)?format=json').then(res => {
        console.log('this.linkedin.getRequest ', res);
})
})`

For the first console.log I get : linkedin signup::results  OK but nothing after that. I am using cordova-plugin-linkedin@1.2.1

**Comment by vinodkalathiya** [comment]
Also I have same problem. It was working a few days ago, just i checked and it is not working now. I am also using ionic 3.

**Comment by TitikshaDaga** [comment]
@vinodkalathiya  I couldn't make this plugin work so I called the LinkedIn Rest APIs

**Comment by binita12345** [comment]
can you please say which api you have used?

**Comment by TitikshaDaga** [comment]
https://developer.linkedin.com/docs/rest-api

The documentation is given in the above link.
