### ISSUE TITLE
getActiveSession always returns true.!

### ISSUE THREAD

**Issue by piyushgahlot** [zyra/cordova-plugin-linkedin#16]
getActiveSession is always returning "true" even when the user is logged out or if we uninstall the app( linkedIn app).

**Comment by ihadeed** [comment]
getActiveSession returns the access token that you app has acquired after using the login method. It has nothing to do with the app being present or not. It just reads the previously stored data.

As far as I know, the plugin only checks if the app exists when you call the login method.
 
Could you please clarify if getActiveSession is returning an access token even if the user never logged in using your app?

**Comment by ihadeed** [comment]
Please read my comment here https://github.com/zyra/cordova-plugin-linkedin/issues/11#issuecomment-302619716

**Comment by piyushgahlot** [comment]
That's okay, getActiveSession returns true only after logging through the app once, but after that when we log out of the linkedin app (ends the session) or uninstall the linkedin app getActiveSession still returns true, I guess then it shall return false and the login method should open the linkedin.com login view and ask user to login but nothing of this sort happens.

**Comment by ihadeed** [comment]
- their native SDK only support login through their official app, you can't login through the web
- as I said in the comment that I linked to previously: If the plugin returns an access token when you call gerActiveSession, then you can use any of other plugin methods and not worry about the app not being present or the user being logged out.
