### ISSUE TITLE
The access_token value is incorrect

### ISSUE THREAD

**Issue by nguyenmanhtuan93** [zyra/cordova-plugin-linkedin#19]
Using your plugin, I get ACCESS_TOKEN, but when calling the linkedin api to retrieve user information with the following link:
[https://api.linkedin.com/v1/people/~:(id,public-profile-url,first-name,last-name,email-address)?format=json&oauth2_access_token=ACCESS_TOKEN](https://api.linkedin.com/v1/people/~:(id,public-profile-url,first-name,last-name,email-address)?format=json&oauth2_access_token=ACCESS_TOKEN)
Then the result returned:
```
{
   "ErrorCode": 0,
   "Message": "Unable to verify access token",
   "RequestId": "PFV0F28P6B",
   "Status": 401,
   "Timestamp": 1498049496692
}
```
Please help me solve this problem, thanks a lot

**Comment by ihadeed** [comment]
See https://github.com/zyra/cordova-plugin-linkedin/issues/1#issuecomment-291118566

**Comment by nguyenmanhtuan93** [comment]
Thank you for the feedback, but the problem I encountered is still unresolved.
I used your api as you instructed in the docs. And here is my code at the frontend:
`
 function loginLinkedln() {
        var scopes = ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'];
        cordova.plugins.LinkedIn.login(scopes, true, function () {
            getActiveSession();
        }, onError);
    }
    var onError = function (e) {
        console.log('LinkedIn Error: ', e);
    }
    function getActiveSession() {
        cordova.plugins.LinkedIn.getActiveSession(function (session) {
            if (session) {
                console.log('We have an active session');
                var **accessToken** = session.accessToken;
                console.log('Access token is: ', session.accessToken);
                console.log('Expires on: ', session.expiresOn);
                //post **accessToken** to my server - backend
            } else {
                console.log('There is no active session');
                vm.loginLinkedln();
            }
        });
    }
`
On the server I hate some user information from Linkedin with **accessToken** received from the frontend, with the get method via the link:
[https://api.linkedin.com/v1/people/~:(id,public-profile-url,first-name,last-name,email-address)?format=json&oauth2_access_token=accessToken](https://api.linkedin.com/v1/people/~:(id,public-profile-url,first-name,last-name,email-address)?format=json&oauth2_access_token=accessToken)
Then Linkedin returns the result:
`
{
   "ErrorCode": 0,
   "Message": "Unable to verify access token",
   "RequestId": "PFV0F28P6B",
   "Status": 401,
   "Timestamp": 1498049496692
}
`
Meanwhile, I use the accessToken code obtained by following the instructions at
[https://developer.linkedin.com/docs/oauth2](https://developer.linkedin.com/docs/oauth2)
to obtain good user information, by replacing the **accessToken** of the above link.
But when replaced with accessToken obtained from your api, the error message as above.
Please look carefully and help me with. Thanks a lot!
