### ISSUE TITLE
The access_token value is incorrect 

### ISSUE THREAD

**Issue by nguyenmanhtuan93** [zyra/cordova-plugin-linkedin#20]
Thank you for the feedback, but the problem I encountered is still unresolved.
I used your api as you instructed in the docs. And here is my code at the frontend:
```
 function loginLinkedln() {
        var scopes = ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'];
        cordova.plugins.LinkedIn.login(scopes, true, function () {
            getActiveSession();
        }, onError);
    }
var onError = function (e) {
     console.log('LinkedIn Error: ', e);
}
function getActiveSession() {
    cordova.plugins.LinkedIn.getActiveSession(function (session) {
         if (session) {
             console.log('We have an active session');
             var **accessToken** = session.accessToken;
             console.log('Access token is: ', session.accessToken);
             console.log('Expires on: ', session.expiresOn);
             //post **accessToken** to my server - backend
         } else {
             console.log('There is no active session');
             loginLinkedln();
         }
      });
 }
```
On the server I hate some user information from Linkedin with **accessToken** received from the frontend, with the get method via the link:
[https://api.linkedin.com/v1/people/~:(id,public-profile-url,first-name,last-name,email-address)?format=json&oauth2_access_token=accessToken](https://api.linkedin.com/v1/people/~:(id,public-profile-url,first-name,last-name,email-address)?format=json&oauth2_access_token=accessToken)
Then Linkedin returns the result:
```
{
   "ErrorCode": 0,
   "Message": "Unable to verify access token",
   "RequestId": "PFV0F28P6B",
   "Status": 401,
   "Timestamp": 1498049496692
}
```
Meanwhile, I use the accessToken code obtained by following the instructions at
[https://developer.linkedin.com/docs/oauth2](https://developer.linkedin.com/docs/oauth2)
to obtain good user information, by replacing the **accessToken** of the above link.
But when replaced with accessToken obtained from your api, the error message as above.
Please look carefully and help me with. Thanks a lot!

**Comment by ihadeed** [comment]
According to the LinkedIn docs, the access token you retrieve via their mobile SDK doesn't work with their web API. So the access token you get from this plugin is useless, I only provide it in case someone wants to do that hack (provided in the link I posted in your previous issue). You need to fool their servers into thinking that you are making the request via a mobile device.

If this trick doesn't work anymore, then there's nothing I can do to help. They probably patched their servers or it's possible that they are using different ways to confirm that you are on a mobile device.

You can still use the `getRequest` and `postRequest` methods to retrieve information from their servers, then send it to your backend.

**Comment by ihadeed** [comment]
If you want to use the access token with your backend, you need to add the following header to your requests: `x-li-src: msdk`

**Comment by nguyenmanhtuan93** [comment]
Thank you for the feedback, getting **accessToken** using the plugin will probably give up. Now I want to ask you, you can get the Authorization Code as in this tutorial [https://developer.linkedin.com/docs/oauth2](https://developer.linkedin.com/docs/oauth2) by still using the plugin.
Regardless of the answer, I also thank you for the feedback! 👍

**Comment by nguyenmanhtuan93** [comment]
Thank you for the feedback, tôi đã giải quyết được vấn đề bằng cách thêm 2 thông số vào phần header

**Comment by Sampath-Lokuge** [comment]
@ihadeed Is this legal or not? I mean using `x-li-src: msdk`? Can you please tell me about it?

**Comment by Sampath-Lokuge** [comment]
@nguyenmanhtuan93 For me `x-li-src: msdk` is not working.What about you?

**Comment by ihadeed** [comment]
@Sampath-Lokuge 

I can't tell you if there are any legal consequences if you use that header, or if it violates their ToS. Their documentation states that the access tokens for web are used for web, and the ones for mobile are only for mobile.

My guess is that if you do anything malicious with that access token (use it in ways that the user did not explicitly authorize), then your LinkedIn app might be disabled. It's unethical anyways to take an access token and use it for purposes that the user did not authorize.

**Comment by Sampath-Lokuge** [comment]
@ihadeed Understood.Thanks alot for your feedback.
