### ISSUE TITLE
I have an issue after I share on LinkedIn

### ISSUE THREAD

**Issue by lethemanh** [zyra/cordova-plugin-linkedin#22]
Error: The operation couldn't be completed(LISDKErrorAPI Domain error 400). This error occur after I share on LinkedIn from my app and I use ionic 1 for my app. Please anyone can help me?

**Comment by ihadeed** [comment]
Can you share the steps you've taken to produce this issue?

**Comment by lethemanh** [comment]
I choose share via LinkedIn on my app then it redirect to LinkedIn app in my phone but after 30s the error occur and I did login to LinkedIn

**Comment by p4ever** [comment]
same here, i simply call this:
` cordova.plugins.LinkedIn.postRequest('~/shares', payload, onSuccess, onError);`
even using the payload in the example i got the same error, maybe it's related with this:
"If you opt to provide a JSON-formatted body, make sure your HTTP request includes the following headers:"

src: https://developer.linkedin.com/docs/share-on-linkedin
