### ISSUE TITLE
finding a person by name

### ISSUE THREAD

**Issue by viksakshum** [zyra/cordova-plugin-linkedin#25]
is it possible to use it to search a public profile by name ? 

lets say the person is found with name then is it possible to find if the person is already my connection or not? 

if yes then can i send a request to connect ?

**Comment by ihadeed** [comment]
I'm not sure if that's allowed by their API. I remember they shut down their People API about 1-2 years ago. 

My guess is if their REST API allows it, you will be able to do that using the `getRequest` method.
