### ISSUE TITLE
Cannot Authenticate the token recieved

### ISSUE THREAD

**Issue by noor92** [zyra/cordova-plugin-linkedin#26]
I am using the getActiveSession function in my ionic 2 project, however, the token that i get back, i can't seem to authenticate it with the LINKEDIN rest console.

**Comment by ihadeed** [comment]
Access tokens provided for mobile SDKs don't work on their HTTP API ... see my response here https://github.com/zyra/cordova-plugin-linkedin/issues/20

**Comment by noor92** [comment]
Adding "x-li-src: msdk" to the header would work like this ? 

let headers = new Headers({ 'Authorization':  x-li-src: msdk });

**Comment by ihadeed** [comment]
`x-li-src` is the header name and `msdk` is the value.
