### ISSUE TITLE
Login, promptToInstall: false, opens Google Play Store for downloading LinkedIn app on Android

### ISSUE THREAD

**Issue by denisx304** [zyra/cordova-plugin-linkedin#29]
Hello, I just tried this piece of code:

```js
var scopes = ['r_basicprofile', 'r_emailaddress'];
		cordova.plugins.LinkedIn.login(scopes, false, function(o) {
			console.log(o);
		}, function() {
			console.error(error);
		});
```
As in documentation: 

> promptToInstall: If set to true, the user will be prompted to install the LinkedIn app if it's not already installed

so it shouldn't taking me to Google Play Store

**Comment by PaolinoD** [comment]
Hi @denisx304,

it's a little tricky, but the true meaning of that boolean is the following:

> A boolean value that determines the behaviour when the LinkedIn app is not installed.  If true, a dialog is shown which prompts the user to install the LinkedIn app via the app store.  If false, the user is taken directly to the app store.

as stated on [official doc](https://developer.linkedin.com/docs/android-sdk-auth).

If you're looking for a way to know if the LinkedIn official app is installed on the device, you have to use a different approach.

As a note, be aware of [issue 17](https://github.com/zyra/cordova-plugin-linkedin/issues/17) for Android platform/devices.
