### ISSUE TITLE
GetActiveSession throws js error on Android

### ISSUE THREAD

**Issue by denisx304** [zyra/cordova-plugin-linkedin#30]
Hi,

I just tried the following piece of code, after login:
`cordova.plugin.LinkedIn.getActiveSession(function(session) {
				console.log(session);
			});`

And this is the error that I am getting:

> Error in Success callbackId: LinkedIn377367718 : TypeError: Cannot read property 'LinkedIn' of undefined (cordova.js:312)

> Uncaught TypeError: Cannot read property 'LinkedIn' of undefined (cordova.js:314)
    at controllers.js:274
    at Object.callbackFromNative (cordova.js:293)
    at <anonymous>:1:9

**Comment by IrfanCALISKAN** [comment]
i have same problem :(

**Comment by ElodieC** [comment]
If it is exactly the code that you wrote, you have a typo. It is `cordova.plugins.LinkedIn.login` at not `cordova.plugin.LinkedIn.login`

**Comment by karthikeyanvgs** [comment]
@IrfanCALISKAN @ElodieC  i have same problem. 

 It is cordova.plugins.LinkedIn.login and not cordova.plugin.LinkedIn.login 

I changed above one also. But still i facing same issue.

**Comment by ElodieC** [comment]
@karthikeyanvgs How did you add the plugin (`cordova plugin add` ?) ? Do you test on a device ? Do you get exactly this error ?

**Comment by karthikeyanvgs** [comment]
@ElodieC  Thanks for your response. 

cordova plugin add cordova-plugin-linkedin --variable APP_ID="4618384"

Test on real devices. Nothing shown. If i give wrong bundle or hash value error function showing correctly(ie bundle id or package name or hash value are mismatched) but success function not return anything.

ionic 1
My Code:
$scope.linkedinlogin = function(){
var onSuccess = function(r) {
alert("onSuccess");
}
var onError = function(e) {
alert(JSON.stringify(e));
console.error('LinkedIn Error: ', e);
}
var scopes = ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'];
cordova.plugins.LinkedIn.login(scopes, true, function() {
cordova.plugins.LinkedIn.getRequest('people/~', onSuccess, onError);
}, onError);
cordova.plugins.LinkedIn.getActiveSession(function(session) {
if (session) {
alert('We have an active session');
} else {
alert('There is no active session, we need to call the login method');
}
});

}

**Comment by karthikeyanvgs** [comment]
@ElodieC Sorry  i Fixed that issue . Thanks for your help.

Below code working correctly:

var onError = function(e) { 
			 alert(JSON.stringify(e));
			console.error('LinkedIn Error: ', e); }
			var onSuccess = function(r) { 
			alert(JSON.stringify(r));
			console.log('LinkedIn Response: ', r); 
}
cordova.plugins.LinkedIn.login(scopes, true, function() { 
				cordova.plugins.LinkedIn.getRequest('people/~:(email-address,first-name)', onSuccess, onError);  
}, onError);
