### ISSUE TITLE
Not compatible with CustomUrlScheme?

### ISSUE THREAD

**Issue by andreamaioli** [zyra/cordova-plugin-linkedin#31]
Hi, in my app I use [CustomUrlScheme](https://github.com/EddyVerbruggen/Custom-URL-scheme) plugin and [Facebook4](https://github.com/jeduan/cordova-plugin-facebook4) plugin.
When I added your plugin, the app stopped to respond to custom url scheme links on IOS devices.

By comparing the code of method **openUrl** in file CDVAppDelegate.m and in AppDelegate+LinkedIn.m I saw that you don't include this line:
```
    // all plugins will get the notification, and their handlers will be called
    [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPluginHandleOpenURLNotification object:url]];

```

By adding the previous line in your file, my app responds correctly. Would you consider to include this modification in your code?

Thanks.

**Comment by ihadeed** [comment]
Sorry I didn't respond earlier. See my response here if you still need an answer --> https://github.com/zyra/cordova-plugin-linkedin/issues/48#issuecomment-362064332
