### ISSUE TITLE
Issues with signup

### ISSUE THREAD

**Issue by popovicidinu** [zyra/cordova-plugin-linkedin#33]
Hi @ihadeed , 

I'm having a really strange issue with the plugin. On my development environment it seems to work on most occasions but when I deploy the app I'm building (release version), sign-in up with LinkedIn doesn't work at all. 

From the adb logs, it seems the plugin throws an error and just hangs. (logs below).

Initially I thought it was from the debug / release key hashes that you have to put on the developer console from LinkedIn, but I've double-triple tested and i'm quite sure I've added the correct ones. 

Also, the error says: USER_CANCELLED. But when I press a button to "sign-up", I see the LinkedIn splash screen and it quickly disappears.

Any thoughts??

```
08-18 18:19:53.435 8245-8245/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 91501 : "{\n  \"errorCode\": \"USER_CANCELLED\",\n  \"errorMessage\": \"user canceled\"\n}"
08-18 18:19:53.435 8245-8245/? I/chromium: [INFO:CONSOLE(91501)] ""{\n  \"errorCode\": \"USER_CANCELLED\",\n  \"errorMessage\": \"user canceled\"\n}"", source: file:///android_asset/www/build/main.js (91501)
08-18 18:19:53.652 1154-1208/? I/ActivityManager: Displayed com.linkedin.android/.liauthlib.thirdparty.LiThirdPartyAuthorizeActivity: +245ms
08-18 18:19:53.961 8245-8245/? D/CordovaActivity: Incoming Result. Request code = 3672
08-18 18:19:53.961 8245-8245/? D/CordovaInterfaceImpl: Sending activity result to plugin
08-18 18:19:53.962 8245-8245/? D/CordovaActivity: Resumed the activity.
``` 

Thanks a lot.

**Comment by PrakharSambhav1** [comment]
Same issue here as well.

**Comment by Denashshaw** [comment]
I too facing this issue anyone got solution ?

**Comment by nissarcs** [comment]
I am also getting same error could some one help me with the issue 
Error logging in {
  "errorCode": "USER_CANCELLED",
  "errorMessage": "user canceled"
}
