### ISSUE TITLE
Issue in publishing app to Apple Store

### ISSUE THREAD

**Issue by RezaRahmati** [zyra/cordova-plugin-linkedin#34]
Hi

When I tried to publish app to app store I get below error message

`ERROR ITMS-90158: "The following URL schemes found in your app are not in the correct format: [li$APP_ID]. URL schemes need to begin with an alphabetic character, and be comprised of alphanumeric characters, the period, the hyphen or the plus sign only. Please see RFC1738 for more detail."`

I found li$APP_ID in xcode project -> Info -> Url Types
Also I found same string in plugin xml file

Do I need to replace it manulally? or what did I miss?

**Comment by ihadeed** [comment]
It should be replaced automatically. 
Did you enter a value for the `APP_ID` variable when installing the plugin?
