### ISSUE TITLE
either bundle id or package name hash are invalid, unknown, malformed

### ISSUE THREAD

**Issue by ashishjnvb** [zyra/cordova-plugin-linkedin#35]
Hi  @ihadeed  @imcu, 

I am getting this error

> {
>	"errorCode": "INVALID_REQUEST",
>	"errorMessage": "either bundle id or package name hash are invalid, unknown, malformed"
> }

I have generated these keys as per documents. 

Thanks.

**Comment by msteptoe** [comment]
Are you still having this issue? If so are you on Android or iOS?

**Comment by pratikbutani** [comment]
Any Solution?

**Comment by msteptoe** [comment]
If you on android then check out https://forum.ionicframework.com/t/key-hash-for-facebook-not-working/44357/5

**Comment by rushabhmakwana** [comment]
Any Solution?
