### ISSUE TITLE
LinkedIn API doesn't retrun any response 

### ISSUE THREAD

**Issue by taha1992** [zyra/cordova-plugin-linkedin#36]
I  created a new app on linkedin and Under the mobile section, pasted package name then generated hash using the following command:

`keytool -exportcert -keystore C:\Users\Sadok\.android\debug.keystore -alias androiddebugkey | openssl sha1 -binary | openssl base64 `

and pasted the hash in the package hash.

**Now when I am trying to call login(), it's not firing up at all, also no response from the linkedin API**

I used the code from your example

**Comment by Borongaj** [comment]
Same here !

hasActiveSession() is fired, but login() freeze the app.

**Comment by shriharip** [comment]
I have almost a similar issue.
I do login() and the linkedin App opens and asks for permission. I grant access. but nothing happens and I get redirected to the login/signup page. In the console log I get a response OK. 
How to get the access token and profile info?
