### ISSUE TITLE
Success Call back not Firing

### ISSUE THREAD

**Issue by karthikeyanvgs** [zyra/cordova-plugin-linkedin#37]
Installed Plugin Version
{
  "_from": "cordova-plugin-linkedin",
  "_id": "cordova-plugin-linkedin@1.2.1",
}

My Code: 
$scope.linkedinlogin = function(){
			var onSuccess = function(r) { 
				alert("onSuccess"); 
			} 
			var onError = function(e) {  
				alert(JSON.stringify(e));
				console.error('LinkedIn Error: ', e); 
			} 
			var scopes = ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share']; 
			cordova.plugins.LinkedIn.login(scopes, true, function() { 
			cordova.plugins.LinkedIn.getRequest('people/~', onSuccess, onError);  
			}, onError); 
			cordova.plugins.LinkedIn.getActiveSession(function(session) {
			if (session) {
				alert('We have an active session'); 
			} else {
				alert('There is no active session, we need to call the login method');
			}
			});

}

ionic 1 

I tried so many times , success function not firing. Anyone please help to resolve this issue.

@ihadeed  @imcu

**Comment by crajbanshi** [comment]
I am using `cordova-plugin-linkedin@1.2.1`  and facing the same problem with IOS.

Hardly finding the solution.

Someone help me to solve the problem.

**Comment by Sharanadhi** [comment]
> I am using `cordova-plugin-linkedin@1.2.1` and facing the same problem with IOS.
> 
> Hardly finding the solution.
> 
> Someone help me to solve the problem.

Hi, im also facing the same issue, did you find any solution for this?
