### ISSUE TITLE
Android login issue: User_cancelled

### ISSUE THREAD

**Issue by danmdinu** [zyra/cordova-plugin-linkedin#41]
Hi, 

When trying to login on Android I'm getting the following error code : "User_cancelled" (. Works fine on ios. 
Any idea what might be wrong and how to overcome this? 

Using:     "cordova-plugin-linkedin": "^1.2.1",

![image](https://user-images.githubusercontent.com/33793329/32985515-348639a2-ccbd-11e7-89c5-24a8a7fdac81.png)

**Comment by PrakharSambhav1** [comment]
Facing the same problem.
I am also using "cordova-plugin-linkedin":"^1.2.1"

**Comment by PrakharSambhav1** [comment]
Is this even active?

**Comment by Denashshaw** [comment]
I too facing this probelm!

**Comment by PrakharSambhav1** [comment]
I too have been waiting for a solution for this issue but no response till yet!

**Comment by PrakharSambhav1** [comment]
Did any one got a solution or a workaround for this?

**Comment by PrakharSambhav1** [comment]
@nissarcs This did not work. Do you have any other solution
