### ISSUE TITLE
Cordova LinkedIn Plugin does not return r_emailaddress

### ISSUE THREAD

**Issue by brasilino** [zyra/cordova-plugin-linkedin#42]
I did the installation and configuration of the plugin. Let me know right away and I have no problem. But email is not returned.

**Look at my setup and code:**

**Default application permissions:**
![linkedin-error](https://user-images.githubusercontent.com/19757021/33321327-78532426-d42c-11e7-9ee1-04e11ec0ec5c.jpg)

**return after login:**
![screenshot_20171128-104556](https://user-images.githubusercontent.com/19757021/33321361-8f3b1676-d42c-11e7-8ba5-07e3612bda37.png)

**code:**
```
loginLinkedIn(): void {

    const scopes:any = ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'];

    this.linkedin.login(scopes, true)
      .then(() => {
        // get connections
        this.linkedin.getRequest('people/~')
        .then(profile => {
          alert(JSON.stringify(profile));
          this.userData = {
            username: profile['headline'],
            picture: '', 
            email: '', 
            first_name: profile['firstName'], 
            last_name: profile['lastName'],
            perfil: profile['siteStandardProfileRequest']['url']
          }
        }).catch(e => alert('Erro get connections: ' + e));
      }).catch(e => alert('Erro Login' + e));

    
  }
```

**development environment:**
nodejs: v8.9.1
npm: 5.5.1
ionic: 3.19.0
cordova: 7.1.0

**Comment by guillaumegarcia13** [comment]
Have you tried?
```this.linkedin.getRequest('people/~:(email-address')```

**Comment by brasilino** [comment]
Thanks for your response. At first it does not work because of a typo in your code. You did not close ")". But thanks to her she was able to find what she needed and that worked for me. Thank you! :)

```
this.linkedin.getRequest('people/~:(id,email-address,firstName,lastName,headline,pictureUrl,public-profile-url,positions:(is-current,company:(name)))?format=json')
        .then(profile => { ...
```
