### ISSUE TITLE
Posting status give error on android

### ISSUE THREAD

**Issue by Zilleabbas10** [zyra/cordova-plugin-linkedin#43]
Everthing is working fine but when i tried to post a status through plugin it results with this (Unknown field {~} in resource {Root}) response and status is not posted. Please check and if there is any solution let me know. Thankyou

**Comment by ihadeed** [comment]
Please provide code sample showing what you're trying to do.

**Comment by winniezz** [comment]
I confirm this is not working as the route seems to be /v1/people/~/shares

code 

cordova.plugins.LinkedIn.postRequest('people/~/shares', payload, function(e) {

is not firing any error

but it's not posting neither :(
