### ISSUE TITLE
Plugin fails to build for android on Ubuntu 17.10

### ISSUE THREAD

**Issue by albe-rosado** [zyra/cordova-plugin-linkedin#44]
running `ionic cordova run android` you get:
`{projectPath}/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:19: error: package com.linkedin.platform does not exist
import com.linkedin.platform.*;
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:20: error: package com.linkedin.platform.errors does not exist
import com.linkedin.platform.errors.LIApiError;
                                   ^
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:21: error: package com.linkedin.platform.errors does not exist
import com.linkedin.platform.errors.LIAuthError;
                                   ^
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:22: error: package com.linkedin.platform.errors does not exist
import com.linkedin.platform.errors.LIDeepLinkError;
                                   ^
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:23: error: package com.linkedin.platform.listeners does not exist
import com.linkedin.platform.listeners.ApiListener;
                                      ^
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:24: error: package com.linkedin.platform.listeners does not exist
import com.linkedin.platform.listeners.ApiResponse;
                                      ^
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:25: error: package com.linkedin.platform.listeners does not exist
import com.linkedin.platform.listeners.AuthListener;
                                      ^
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:26: error: package com.linkedin.platform.listeners does not exist
import com.linkedin.platform.listeners.DeepLinkListener;
                                      ^
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:27: error: package com.linkedin.platform.utils does not exist
import com.linkedin.platform.utils.Scope;
                                  ^
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:28: error: package com.linkedin.platform.utils.Scope does not exist
import com.linkedin.platform.utils.Scope.LIPermission;
                                        ^
/home/albe/Documents/Jobs/jobs/platforms/android/app/src/main/java/com/zyramedia/cordova/linkedin/LinkedIn.java:38: error: cannot find symbol
    private LISessionManager liSessionManager;`

**Comment by albe-rosado** [comment]
`
cli packages: (/home/albe/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.3.0
    npm               : 5.5.1 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/albe/Android/Sdk

Misc:

    backend : pro
`

**Comment by albe-rosado** [comment]
well, same in MacOS, i believe is a java thing,...

**Comment by jamesYapKM** [comment]
same error here.

**Comment by ihadeed** [comment]
Hey guys

Are you all using Cordova 8?

Can you stick with Cordova 7 and Cordova-Android ^6.4.0 for now?

**Comment by jamesYapKM** [comment]
i found an solution, it is work for me:
just change the following setting in cordova-plugin-linkedin/plugin.xml
<resource-file src="src/android/linkedin.jar" target="libs/linkedin.jar" reference="true"/>
<lib-file src="src/android/linkedin.jar"/>

**Comment by albe-rosado** [comment]
@ihadeed I was using Cordova 7 when that happened, somehow the java files can’t import that LinkedIn.jar , will try @jamesYapKM suggestion and report back ASAP, and thank you for your patience and efforts.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by albe-rosado** [comment]
@jamesYapKM  Your workaround works fine. Thank you. @ihadeed

**Comment by lucasbasquerotto** [comment]
I've tried the solution above but wasn't able to make it work (I've received the same errors). I could make it work **changing the linkedin gradle file** inside `/platforms/android/cordova-plugin-linkedin/` from:

```
dependencies {
  compile 'com.mcxiaoke.volley:library:1.0.+'
}
```

to:

```
dependencies {
  compile 'com.mcxiaoke.volley:library:1.0.+'
  compile files('src/main/libs/linkedin.jar')
}
```

I think I will create a hook script to avoid manual changes to the `platforms` folder.

**Comment by sufiyaq** [comment]
Getting same error, tried changing plugin.xml and adding dependencies but neither of is working for me.

**Comment by albe-rosado** [comment]
@sufiyaq  what platform are you using?

**Comment by sufiyaq** [comment]
@albe-rosado I am using android and ios platform, however the build is working fine for ios and gives error for android.

**Comment by albe-rosado** [comment]
@sufiyaq yeah, for ios works fine, the problem is with the plugin's jar file. Try what ihadeed or lucas did. good luck!

**Comment by brasilino** [comment]
I had the same problem and at first the @jamesYapKM solution did not work for me. But after adding the remove the android platform worked. Thank you!

**Comment by devfelipereis** [comment]
Same here. @lucasbasquerotto solution works.
