### ISSUE TITLE
[Compile time] package com.linkedin.platform does not exist

### ISSUE THREAD

**Issue by guillaumegarcia13** [zyra/cordova-plugin-linkedin#46]
Hi,

Got an error when compiling:
> C:\<project root>\platforms\android\app\src\main\java\com\zyramedia\cordova\linkedin\LinkedIn.java:19: error: package com.linkedin.platform does not exist
> import com.linkedin.platform.*;

I am developing Ionic 3 app on Windows 10.
Shouldn't I add the LinkedIn Native SDK in my project?
https://developer.linkedin.com/downloads#androidsdk

**Comment by ihadeed** [comment]
What version of `cordova` and what version of `cordova-android` ?

**Comment by ihadeed** [comment]
See the last few comments here https://github.com/zyra/cordova-plugin-linkedin/issues/44

**Comment by guillaumegarcia13** [comment]
Hi,
Thank you!!
The addition of ```compile files('src/main/libs/linkedin.jar')``` in '\node_modules\cordova-plugin-linkedin\src\android\LinkedIn.gradle' did the trick!
