### ISSUE TITLE
LinkedIn API v2

### ISSUE THREAD

**Issue by guillaumegarcia13** [zyra/cordova-plugin-linkedin#47]
Hi,
Just wondering whether you have tried implementing **API v2**?
https://github.com/nickls/linkedin-unofficial-api

Do you know if this requires an additional validation process on LinkedIn side (I mean in addition to declaring one's app at: https://www.linkedin.com/developer/apps/)?

Many thanks in advance for your insights.

**Comment by ihadeed** [comment]
- No, this is my first time seeing that unofficial API. Looks like it's a HTTP based API, there is no need for a Cordova plugin.

- There are no further requirements.

**Comment by tobiasmuecksch** [comment]
What about the official v2 api?

https://developer.linkedin.com/docs/guide/v2
