### ISSUE TITLE
either bundle id or package name hash are invalid, unknown, malformed

### ISSUE THREAD

**Issue by rushabhmakwana** [zyra/cordova-plugin-linkedin#49]
Hi @ihadeed @imcu,

I am getting this error when try to login with LinkedIn

{
"errorCode": "INVALID_REQUEST",
"errorMessage": "either bundle id or package name hash are invalid, unknown, malformed"
}

I have generated these keys as per documents.

**Comment by manunavarrofunciona** [comment]
You have to configure your Linkedin App in your LinkedIn developer account, 

You have to do as follows:

1 - Generate a debug key
2 - Get that key hash
3 - Write that key hash and the bundle id in your Linkedin App (in developer account)
4 - Build your app and sign with the debug key

Hope it helps! :)
