### ISSUE TITLE
Nothing is fired on Android where there is no LinkedIn installed

### ISSUE THREAD

**Issue by franzisk** [zyra/cordova-plugin-linkedin#52]
Hi,
I have this simple call to login, but when executed nothing is fired, nor the catch nor the then.

 ```
 async loginWithLinkedin() {
    console.log('Login with Linkedin (1) - OK');
    try {
      console.log('Login with Linkedin (2) - Ok until here');
      this.linkedin.login(this.linkedinScopes, true).then(response => {
        console.log('Login with Linkedin (3) - not printed ');
        console.log(JSON.stringify(response));
      }).catch(error => {
        console.log('Login with Linkedin (4) - not printed');
        console.log(JSON.stringify(error));
      });
    } catch (error) {
      this.global.showError('LinkedIn Error', error);
      console.log("LinkedIn Error: " + JSON.stringify(error));
    }
  }
```
The LinkedIn app is not installed on this device, I want my app prompts and ask to install.

Any ideas?

**Comment by Wolf00Bomber** [comment]
Install the Linked In App on the Device, and then these issues will be fixed. I did that and now i am seeing the Login Permisison Prompt.

**Comment by franzisk** [comment]
@Wolf00Bomber I installed LinkedIn App and now the "**response**" returns "OK" but just that, I need at least email, name and picture. Is that normal?

**Comment by lucasbasquerotto** [comment]
This seems like a bug in the plugin (or in the ionic wrapper). **It should return a response even if the app is not installed** (the response could be an error in such a case).

**Comment by zen4raul** [comment]
any update on this ? I am also receiving similar error..it does not throw any error or any prompt to install..
