### ISSUE TITLE
[iOS] Login Failed

### ISSUE THREAD

**Issue by kunalkakkad** [zyra/cordova-plugin-linkedin#56]
Hello,

I am facing error in login() of linkedin and the error states as follows:

_"The operation couldn’t be completed. (LISDKAuthError error 1.)"_

Facing this issue only in iOS.

Please help me out.

Thanks,
Kunal Kakkad

**Comment by DydjyZ** [comment]
Hello Kunal !

Got the same error, do you found a solution ?

Dylan
