### ISSUE TITLE
How to get a user's email?

### ISSUE THREAD

**Issue by thecodie** [zyra/cordova-plugin-linkedin#57]

**Comment by CRedTec** [comment]
Hi @thecodie ,

1. You need to enable the permission to read email in your LinkedIn app **"r_emailaddress"**.

2. You need to add the permission in to login service in your Ionic app **"r_emailaddress"**.

`this.linkedin.login(['r_basicprofile', 'r_emailaddress'], true).then(....).catch(...);`

3. After request login with this.linkedin.login in your app, get information of user and add the field to call and return email with response.
`this.linkedin.getRequest('people/~:(email-address,id,formatted-name,headline,picture-urls::(original))').then(res=>{
    console.log(res.emailAddress);
})`

**Comment by UTSOURCE** [comment]
Have you solved it? I also encountered the same problem
