### ISSUE TITLE
cordova linkedin login issue 

### ISSUE THREAD

**Issue by Denashshaw** [zyra/cordova-plugin-linkedin#58]
var scopes = ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'];

var onSuccess = function(r) { myApp.alert('LinkedIn Response: ', r); } var onError = function(e) { myApp.alert('LinkedIn Error: ', e); }

cordova.plugins.LinkedIn.login(scopes, true, function() { cordova.plugins.LinkedIn.getRequest('people/~:(email-address,first-name)', onSuccess, onError); }, onError);

Linkedin login using cordova i added this plugin cordova plugin add cordova-plugin-linkedin --variable APP_ID=YOUR_APP_ID

Example of this code taken from this page ------ https://www.npmjs.com/package/cordova-plugin-linkedin

While i am trying to login in linkedin the splashscreen of linkedin app disppears in seconds and in alert error this is coming **"{\n \"errorCode\": \"USER_CANCELLED\",\n \"errorMessage\": \"user canceled\"\n}"**

But when i logging in first time the linkedin app just opens as normal but getting this error myApp.alert('LinkedIn Error: ', e);

Can anyone please help me to fix it? If there is any links available also let me know.

**Comment by UTSOURCE** [comment]
Have you solved it? I also encountered the same problem
