### ISSUE TITLE
does not get any response 

### ISSUE THREAD

**Issue by raj003** [zyra/cordova-plugin-linkedin#61]
I have installed the plugin and configured it in the linkedin website 
![lk pg](https://user-images.githubusercontent.com/40828500/44601762-2ab5fd80-a7fb-11e8-91df-8a5156c5bf79.PNG)
This is my code 
```
scopes: LinkedInLoginScopes[] = ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'];
linkedinLogin() : void {
    this.linkedin.login(this.scopes, true)
      .then(() => {
        // get connections
        this.linkedin.getRequest('people/~:(id,email-address,firstName,lastName,headline,pictureUrl,public-profile-url,positions:(is-current,company:(name)))?format=json')
        .then(profile => {
          alert(JSON.stringify(profile));
          this.userData = {
            username: profile['headline'],
            picture: '', 
            email: '', 
            first_name: profile['firstName'], 
            last_name: profile['lastName'],
            perfil: profile['siteStandardProfileRequest']['url']
          }
        }).catch(e => alert('Erro get connections: ' + e));
      }).catch(e => alert('Erro Login' + e));
  }

```
when I click on the button(linkedinLogin()) I don't get any response nor it does through any error. just no action takes place.

**Comment by alexander171294** [comment]
In first instance, this run only in android/ios, in the web version isn't work.

Another question is this plugin launch linkedin app for login (you need to have installed this), theoretically this launch the playstore if the linkedin app isn't installed, but if you don't have configured permissions for this, the playstore is not launched.

**Comment by Sharanadhi** [comment]
> I have installed the plugin and configured it in the linkedin website
> ![lk pg](https://user-images.githubusercontent.com/40828500/44601762-2ab5fd80-a7fb-11e8-91df-8a5156c5bf79.PNG)
> This is my code
> 
> ```
> scopes: LinkedInLoginScopes[] = ['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'];
> linkedinLogin() : void {
>     this.linkedin.login(this.scopes, true)
>       .then(() => {
>         // get connections
>         this.linkedin.getRequest('people/~:(id,email-address,firstName,lastName,headline,pictureUrl,public-profile-url,positions:(is-current,company:(name)))?format=json')
>         .then(profile => {
>           alert(JSON.stringify(profile));
>           this.userData = {
>             username: profile['headline'],
>             picture: '', 
>             email: '', 
>             first_name: profile['firstName'], 
>             last_name: profile['lastName'],
>             perfil: profile['siteStandardProfileRequest']['url']
>           }
>         }).catch(e => alert('Erro get connections: ' + e));
>       }).catch(e => alert('Erro Login' + e));
>   }
> ```
> when I click on the button(linkedinLogin()) I don't get any response nor it does through any error. just no action takes place.

hi raj,
I am also facing the same issue, did you find any solution for this?
