### ISSUE TITLE
Login does not work if LinkedIn App is opened.

### ISSUE THREAD

**Issue by ajay92x** [zyra/cordova-plugin-linkedin#63]
I've integrated this plugin in Ionic 4. 
Everything is working fine in Android but in iOS it only works if LinkedIn app is closed.
Once I login with LinkedIn it works but after logout and login again it does not work.
Here is the code which I'm using:

this.linkedin.login(['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'], true)
			.then((res) => {
				console.log("LOGIN DATA:", JSON.stringify(res));
				alert("LOGIN DATA:\n" + JSON.stringify(res));

				this.linkedin.getActiveSession().then((response) => {
					console.log("ACTIVE DATA:", JSON.stringify(response));
					alert("ACTIVE DATA:\n" + JSON.stringify(response));

					this.linkedin.getRequest('people/~')
						.then(callback => {
							console.log("REQUEST DATA:", JSON.stringify(callback));
						})
						.catch(e => {
							console.log('Error getting personal details from LinkedIn: ', e);
							alert("Error getting personal details from LinkedIn: \n" + JSON.stringify(e));
						});
				});

			})
			.catch(e => {
				console.log('Error logging in', e);
				alert("Error logging in: \n" + JSON.stringify(e));
			});

**Comment by caominhthe** [comment]
I got same issue. Do you find a work around or something?

**Comment by ajay92x** [comment]
I'm still facing the same issue.

For now I'm using below code where I'm checking for active session first and based on that getting the token and then requesting for data. Let me know if you can find any better solution.

Here is the code:

this.linkedin.hasActiveSession()
			.then((response) => {
				if (response === true) {
					this.getToken();
				} else {
					this.login();
				}
			})
			.catch(e => {
				console.log('Error:’, e);
			});

login() {
		this.linkedin.login(['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share'], true)
			.then((res) => {
				this.getToken();
			})
			.catch(e => {
				console.log('Error:’, e);
			});
	}

	getToken() {
		this.linkedin.getActiveSession()
			.then((res) => {
				this.getRequest(res);
			})
			.catch(e => {
				console.log('Error:’, e);
			});
	}

	getRequest(response) {
		this.linkedin.getRequest('people/~’)
			.then(data => {
				console.log("DATA:", JSON.stringify(data));
			})
			.catch(e => {
				console.log('Error:’, e);
			});
	}
