### ISSUE TITLE
Can't login to Linkedin if Linkedin app is not installed on the device

### ISSUE THREAD

**Issue by msmadja** [zyra/cordova-plugin-linkedin#65]
Im using this plugin in my project and when I click on Login to linkedin it always asks from me to install the app in the device. 

is it not working without installing the Linkedin app?

**Comment by msmadja** [comment]
any solution?

**Comment by ihadeed** [comment]
That's how their SDK works; it only allows logging in through the app -- they don't allow browser based login.
