### ISSUE TITLE
Can't login (Android/iOS)

### ISSUE THREAD

**Issue by DydjyZ** [zyra/cordova-plugin-linkedin#66]
Hello,

Since some days, i can't login with the LinkedIn Login, also with my app who is on the store.. 

I saw that LinkedIn announced that all developers needs to migrate to V2 to their API by March 1. 

My app is still OK in the linkedin developer dashboard.

-----

Code side : 

    this.linkedin.login(this.scopes, true).then((data) => {
        console.log('Logged in!', data);
        this.linkedin.hasActiveSession().then((active) => {
          console.log("LINKEDIN SESSION", active);
        });
     });

Console returns : 

- Logged in!, Ok
- LINKEDIN SESSION, false

Does anyone has a solution to get my LinkedIn Login back ?

**Comment by TitikshaDaga** [comment]
Hi @DydjyZ. Were you able to solve this issue? I am facing the same problem.

**Comment by 0x15f** [comment]
Facing the same issue

**Comment by msmadja** [comment]
I'm facing the same problem.
I'm trying to login and then getActiveSession and  I get no session.
Can you please fix this bug?

**Comment by 0x15f** [comment]
This isn't a bug, LinkedIn OAuth v1 was depreciated, no mobile SDK's work anymore you have to use OAuth v2.

**Comment by antgel** [comment]
@0x15f Thanks for the input. What's the workaround (or better - correct solution moving forward)? Fix the plugin to use OAuth2 instead of the mobile SDKs? Or move to https://github.com/nraboy/ngx-cordova-oauth (we're using Angular 2+).

**Comment by 0x15f** [comment]
@antgel I think it'd be a waste to update this plugin, I think the other could work or using the InAppBrowser to redirect and capture the oauth tokens.

**Comment by RezaRahmati** [comment]
> @0x15f Thanks for the input. What's the workaround (or better - correct solution moving forward)? Fix the plugin to use OAuth2 instead of the mobile SDKs? Or move to https://github.com/nraboy/ngx-cordova-oauth (we're using Angular 2+).

That library doesn't support Google any more
