### ISSUE TITLE
'getRequest' method does not fire any callback either iOS or Android

### ISSUE THREAD

**Issue by rushabhmakwana** [zyra/cordova-plugin-linkedin#68]
I am using this plugin for doing sign in through LinkedIn in my ionic1 version app. 'login' method working fine for this plugin, but 'getRequest' method for getting user profile detail does not fire any callback. Below is my code

       var scopes = ['r_basicprofile', 'r_emailaddress'];
        cordova.plugins.LinkedIn.login(scopes, true, function (response) {
            cordova.plugins.LinkedIn.getRequest('people/~:(id,first-name,last-name,email-address)?format=json', function (userDetail) {
            }, function (error) {
            });
        }, function (error) {
        });

Please help ASAP.

**Comment by Sharanadhi** [comment]
> I am using this plugin for doing sign in through LinkedIn in my ionic1 version app. 'login' method working fine for this plugin, but 'getRequest' method for getting user profile detail does not fire any callback. Below is my code
> 
> ```
>    var scopes = ['r_basicprofile', 'r_emailaddress'];
>     cordova.plugins.LinkedIn.login(scopes, true, function (response) {
>         cordova.plugins.LinkedIn.getRequest('people/~:(id,first-name,last-name,email-address)?format=json', function (userDetail) {
>         }, function (error) {
>         });
>     }, function (error) {
>     });
> ```
> Please help ASAP.

Hi Rushabh,
Im also facing the same issue did you find and solution for this?

**Comment by rushabhmakwana** [comment]
@Sharanadhi No, I didn't get any solution with this plugin. But I have implemented Login with LinkedIn functionality with the alternative way via $cordovaOauth(http://ngcordova.com/docs/plugins/oauth/) plugin.
