### ISSUE TITLE
TODO: ability to get the OAuth access token

### ISSUE THREAD

**Issue by ihadeed** [zyra/cordova-plugin-linkedin#8]

**Comment by ihadeed** [comment]
This is now added and available in version `1.2.0` or later.

**Comment by AdrienDC** [comment]
@ihadeed version 1.2.0 hasn't be released?

**Comment by ihadeed** [comment]
@AdrienDC it is released. If you run the command `npm show cordova-plugin-linkedin` you will see there is `1.2.0` and `1.2.1`

**Comment by AdrienDC** [comment]
Thanks, I can see it now. Really love this plugin )
